force-app/main/default/objects/ECP_PrinterManagement__c/ECP_PrinterManagement__c.object-meta.xml
<CustomObject>
    <label>印刷サービス設定</label>
    <nameField>
        <label>印刷サービス名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ECP_PrinterManagement__c/fields/ContractId__c.field-meta.xml
<CustomField>
    <fullName>ContractId__c</fullName>
    <label>契約ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ECP_PrinterManagement__c/fields/ServiceUrl__c.field-meta.xml
<CustomField>
    <fullName>ServiceUrl__c</fullName>
    <label>サービスURL</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ECP_PrintTemplate__c/ECP_PrintTemplate__c.object-meta.xml
<CustomObject>
    <label>テンプレート</label>
    <nameField>
        <displayFormat>PMSPT-{000000}</displayFormat>
        <label>印刷テンプレート管理番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ECP_PrintTemplate__c/fields/JsonConfigVal__c.field-meta.xml
<CustomField>
    <fullName>JsonConfigVal__c</fullName>
    <label>テンプレート配置</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ECP_PrintTemplate__c/fields/TemplateName__c.field-meta.xml
<CustomField>
    <fullName>TemplateName__c</fullName>
    <label>テンプレート名</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ECP_TemplateCenterSetting__c/ECP_TemplateCenterSetting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>eDocumentカスタム設定</label>
</CustomObject>

force-app/main/default/objects/ECP_TemplateCenterSetting__c/fields/TemplateCenterUrl__c.field-meta.xml
<CustomField>
    <fullName>TemplateCenterUrl__c</fullName>
    <defaultValue>&quot;https://ecloudsoft.github.io&quot;</defaultValue>
    <label>テンプレート参照リンク</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/ECP_PrintPreviewCompCtrl.cls
public with sharing class ECP_PrintPreviewCompCtrl {
  // 印刷サービス名
  public String printSeviceNameEcp { get; set; }
  // 印刷テンプレート名
  public List<String> templateNameEcp { get; set; }
  // 印刷テンプレート  テンプレート配置
  public String printConfigStr { get; set; }
  // サービスURL(本地打印)
  public String serviceURL { get; set; }
  // 契约Id(云打印)
  public String contractId { get; set; }
  // CSS URL
  public String cssBaseUrl { get; set; }

  public String getInitAction() {
    cssBaseUrl = ECP_TemplateCenterSetting__c.getOrgDefaults()
      .TemplateCenterUrl__c;
    // 印刷テンプレート
    SObjectAccessDecision templatesSecurity = Security.stripInaccessible(
      AccessType.READABLE,
      [
        SELECT Id, templateName__c, JsonConfigVal__c
        FROM ECP_PrintTemplate__c
        WHERE templateName__c = :templateNameEcp
      ]
    );
    List<ECP_PrintTemplate__c> templates = (List<ECP_PrintTemplate__c>) templatesSecurity.getRecords();
     if(templates.isEmpty()){
      return '印刷テンプレート名だ見つかりませんでした';
    }
    // 查询结果排序
    Map<String, ECP_PrintTemplate__c> templateMap = new Map<String, ECP_PrintTemplate__c>();
    for (ECP_PrintTemplate__c template : templates) {
        templateMap.put(template.templateName__c, template);
    }
    List<ECP_PrintTemplate__c> sortedTemplates = new List<ECP_PrintTemplate__c>();
    for (String name : templateNameEcp) {
      if(templateMap.get(name) != null){
        sortedTemplates.add(templateMap.get(name));
      }
    }

    // 合并panels
    List<Object> mergedPanels = new List<Object>();
    for(ECP_PrintTemplate__c t : sortedTemplates){
      Map<String, Object> map1 = (Map<String, Object>) JSON.deserializeUntyped(t.JsonConfigVal__c);
      List<Object> panels1 = (List<Object>) map1.get('panels');
      mergedPanels.addAll(panels1);
    }
    Map<String, Object> mergedMap = new Map<String, Object>();
    mergedMap.put('panels', mergedPanels);

    printConfigStr = JSON.serialize(mergedMap);
    
    // 印刷サービス
    SObjectAccessDecision serviceSecurity = Security.stripInaccessible(
      AccessType.READABLE,
      [
        SELECT Id, ServiceUrl__c, ContractId__c
        FROM ECP_PrinterManagement__c
        WHERE Name = :printSeviceNameEcp
      ]
    );

    List<ECP_PrinterManagement__c> printSevices = (List<ECP_PrinterManagement__c>) serviceSecurity.getRecords();
    if (printSevices != null && !printSevices.isEmpty()) {
      // 印刷サービス  サービスURL
      serviceURL = printSevices[0].ServiceUrl__c;
      // 印刷サービス  契约Id
      contractId = printSevices[0].ContractId__c;
    } else{
      return '印刷サービスだ見つかりませんでした';
    }
    return '';
  }
}